version: '3'
services:
  backend:
    image: my-backend-image
    ports:
      - '3333:3333'
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit
